name: siaas
description: SIAAS (Sistema Inteligente de Alertas AgrÃ­colas - Offline)
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ðŸ” Persistencia
  shared_preferences: ^2.5.4

  # ðŸŒ Red y conectividad
  http: ^1.2.0
  connectivity_plus: ^6.0.3

  # ðŸ“ UbicaciÃ³n
  geolocator: ^10.1.1

  # ðŸ–¼ï¸ ImÃ¡genes
  image_picker: ^1.0.7

  # ðŸ” Permisos
  permission_handler: ^11.4.0

  # ðŸ—„ï¸ Base de datos local
  sqflite: ^2.3.3
  path: ^1.9.0

  # ðŸŒ InternacionalizaciÃ³n / UI
  intl: ^0.19.0
  cupertino_icons: ^1.0.6
  characters: ^1.4.0
  meta: ^1.16.0
  material_color_utilities: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^6.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_siaas_launcher.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
